<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategoriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('categories')->insert([
            [
                'id' => 4,
                'category_name' => 'Vodka',
                'image' => '1613238015_unnamed (3).jpg',
                'description' => 'Fijnste vodka\'s voor uw genot.',
                'is_popular' => false,
                'category_order' => 16,
                'category_id' => null,
                'is_show' => 0,
                'product_type_id' => null,
                'created_at' => '2020-09-12 01:38:06',
                'updated_at' => '2024-02-27 12:17:02',
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'category_name' => 'Sparkling & Prosecco',
                'image' => '1613234750_81dWznuEIFL._AC_SL1500_.jpg',
                'description' => 'Heerlijk bruisende Prosseco\'s en bubbels',
                'is_popular' => false,
                'category_order' => 8,
                'category_id' => null,
                'is_show' => 1,
                'product_type_id' => 2,
                'created_at' => '2021-02-13 15:27:07',
                'updated_at' => '2024-02-27 12:17:02',
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'category_name' => 'Champagne & Cava',
                'image' => '1613233460_Category-Mobile-Moet_1.jpg',
                'description' => 'Altijd een goed moment voor de meest fantastische Champagnes en Cavas',
                'is_popular' => false,
                'category_order' => 9,
                'category_id' => null,
                'is_show' => 1,
                'product_type_id' => 2,
                'created_at' => '2021-02-13 15:28:06',
                'updated_at' => '2024-02-27 12:17:02',
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'category_name' => 'Johnnie Walker',
                'image' => '1613236825_johnnie-walker.jpg',
                'description' => 'Johnnie Walker werd voor het eerst gemaakt in een eenvoudige kruidenierswinkel en heeft blended Scotch whisky uit de vier hoeken van Schotland naar de vier uithoeken van de wereld gebracht. Tegenwoordig heeft deze pioniersgeest en innovatieve geest het merk tot een stijlvol wereldwijd icoon gemaakt.',
                'is_popular' => false,
                'category_order' => 0,
                'category_id' => null,
                'is_show' => 1,
                'product_type_id' => null,
                'created_at' => '2020-09-12 02:24:37',
                'updated_at' => '2021-03-17 16:09:34',
                'deleted_at' => '2021-06-07 13:39:02',
            ],
            [
                'id' => 6,
                'category_name' => 'Whisky',
                'image' => '1613236165_samenstelling-met-flessen-van-populaire-whiskymerken-81418475.jpg',
                'description' => 'De meest bijzondere whisky merken voor u geselecteerd',
                'is_popular' => false,
                'category_order' => 15,
                'category_id' => null,
                'is_show' => 0,
                'product_type_id' => null,
                'created_at' => '2020-09-12 02:32:52',
                'updated_at' => '2024-02-27 12:17:02',
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'category_name' => 'Ready-To-Drink',
                'image' => '1613230927_hero-3-cans-lg-561x640.png',
                'description' => 'Voor uw gemak voor de bekendste voor gemixte dranken en hard seltzers',
                'is_popular' => false,
                'category_order' => 10,
                'category_id' => null,
                'is_show' => 1,
                'product_type_id' => 4,
                'created_at' => '2021-02-13 15:29:37',
                'updated_at' => '2024-02-27 12:17:02',
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'category_name' => 'test123',
                'image' => '1600778104_download.jpg',
                'description' => 'test123',
                'is_popular' => false,
                'category_order' => 0,
                'category_id' => null,
                'is_show' => 1,
                'product_type_id' => null,
                'created_at' => '2020-09-22 07:04:45',
                'updated_at' => '2020-09-22 07:05:17',
                'deleted_at' => '2020-09-22 07:05:17',
            ],
            [
                'id' => 8,
                'category_name' => 'Test Category',
                'image' => '',
                'description' => 'Meaningful description',
                'is_popular' => false,
                'category_order' => 0,
                'category_id' => null,
                'is_show' => 1,
                'product_type_id' => null,
                'created_at' => '2020-12-03 07:09:32',
                'updated_at' => '2021-01-11 10:52:39',
                'deleted_at' => '2021-01-11 10:52:39',
            ],
            [
                'id' => 9,
                'category_name' => 'Bottleservice',
                'image' => '1613236125_20210213_180821.jpg',
                'description' => 'Bottleservice',
                'is_popular' => false,
                'category_order' => 1,
                'category_id' => null,
                'is_show' => 1,
                'product_type_id' => 2,
                'created_at' => '2021-01-11 06:17:13',
                'updated_at' => '2024-02-27 12:17:02',
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'category_name' => 'Bier',
                'image' => '1613235478_bierprijzen-flessen.png',
                'description' => 'De beste binnenlandse bieren voor uw op een rij.',
                'is_popular' => false,
                'category_order' => 3,
                'category_id' => null,
                'is_show' => 1,
                'product_type_id' => null,
                'created_at' => '2021-01-11 10:54:12',
                'updated_at' => '2024-02-27 12:17:02',
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'category_name' => '247DRANK DEALS',
                'image' => '1613239550_Black_Friday_2019_Deals_3.jpg',
                'description' => 'Elke dag een van je favoriete dranken in een deal.',
                'is_popular' => false,
                'category_order' => 2,
                'category_id' => null,
                'is_show' => 1,
                'product_type_id' => 12,
                'created_at' => '2021-01-11 11:01:01',
                'updated_at' => '2024-02-27 12:17:02',
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'category_name' => 'Speciale bieren',
                'image' => '1610367500_Store.jpg',
                'description' => 'Een overzicht van de beste en lekkerste internationale bieren voor u uitgezocht.',
                'is_popular' => false,
                'category_order' => 4,
                'category_id' => null,
                'is_show' => 1,
                'product_type_id' => null,
                'created_at' => '2021-01-11 12:07:58',
                'updated_at' => '2024-02-27 12:17:02',
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'category_name' => 'Populaire dranken',
                'image' => '',
                'description' => 'De meest populaire dranken van dit moment',
                'is_popular' => false,
                'category_order' => 10,
                'category_id' => null,
                'is_show' => 1,
                'product_type_id' => null,
                'created_at' => '2021-02-13 14:47:42',
                'updated_at' => '2021-10-19 21:35:11',
                'deleted_at' => '2021-10-19 21:35:11',
            ],
            [
                'id' => 14,
                'category_name' => 'Wijn',
                'image' => '1613235080_Top-15-Chardonnay-wijnen-om-te-drinken-in-2020-–-Beste-wijn-om-te-kopen.jpg',
                'description' => 'Uit de meest fantastische wijngaarden!',
                'is_popular' => false,
                'category_order' => 5,
                'category_id' => null,
                'is_show' => 1,
                'product_type_id' => 2,
                'created_at' => '2021-02-13 14:57:44',
                'updated_at' => '2024-02-27 12:17:02',
                'deleted_at' => null,
            ],
            [
                'id' => 18,
                'category_name' => 'Soda & Energy',
                'image' => '1613230751_1610362923_12323.jpg',
                'description' => 'Lekker fris om te mixen of ga voor een stevige energie boost!',
                'is_popular' => false,
                'category_order' => 11,
                'category_id' => null,
                'is_show' => 1,
                'product_type_id' => 8,
                'created_at' => '2021-02-13 15:35:52',
                'updated_at' => '2024-02-27 12:17:02',
                'deleted_at' => null,
            ],
            [
                'id' => 19,
                'category_name' => '247DRANQUILLO',
                'image' => '1613237390_download.jpeg',
                'description' => 'Top selectie van de lekkerste alcoholvrij versnaperingen.',
                'is_popular' => false,
                'category_order' => 20,
                'category_id' => 19,
                'is_show' => 1,
                'product_type_id' => null,
                'created_at' => '2021-02-13 17:29:51',
                'updated_at' => '2021-09-16 14:57:18',
                'deleted_at' => null,
            ],
            [
                'id' => 20,
                'category_name' => 'Cocktails',
                'image' => '1613237466_cocktails-fuer-den-sommer.jpg',
                'description' => 'De beste cocktails dagvers gemaakt door onze cocktail shakers.',
                'is_popular' => false,
                'category_order' => 12,
                'category_id' => null,
                'is_show' => 0,
                'product_type_id' => 4,
                'created_at' => '2021-02-13 17:31:06',
                'updated_at' => '2024-02-27 12:17:02',
                'deleted_at' => null,
            ],
            [
                'id' => 21,
                'category_name' => 'test',
                'image' => '',
                'description' => 'test',
                'is_popular' => false,
                'category_order' => 0,
                'category_id' => null,
                'is_show' => 1,
                'product_type_id' => null,
                'created_at' => '2021-03-17 16:52:52',
                'updated_at' => '2021-03-17 17:37:24',
                'deleted_at' => '2021-03-17 17:37:24',
            ],
            [
                'id' => 22,
                'category_name' => 'Wijn Middle',
                'image' => '',
                'description' => 'Wijn van midden standaard',
                'is_popular' => false,
                'category_order' => 6,
                'category_id' => null,
                'is_show' => 0,
                'product_type_id' => 2,
                'created_at' => '2021-03-25 15:05:33',
                'updated_at' => '2024-02-27 12:17:02',
                'deleted_at' => null,
            ],
            [
                'id' => 23,
                'category_name' => 'Wijn High-End',
                'image' => '',
                'description' => 'Exclusieve wijnen \r\nSegment: High-End',
                'is_popular' => false,
                'category_order' => 7,
                'category_id' => null,
                'is_show' => 0,
                'product_type_id' => 2,
                'created_at' => '2021-03-25 15:29:16',
                'updated_at' => '2024-02-27 12:17:02',
                'deleted_at' => null,
            ],
            [
                'id' => 24,
                'category_name' => 'Jaanu Juice',
                'image' => '',
                'description' => 'Daily Fresh Tropical and domestic Juices by Jaanu',
                'is_popular' => false,
                'category_order' => 18,
                'category_id' => null,
                'is_show' => 0,
                'product_type_id' => null,
                'created_at' => '2021-03-25 16:47:19',
                'updated_at' => '2024-02-27 12:17:02',
                'deleted_at' => null,
            ],
            [
                'id' => 25,
                'category_name' => 'Jaanu Cocktails',
                'image' => '',
                'description' => 'Fresh made Cocktails by Jaanu\r\nOur best international cocktail bartenders have made a selection of the finest cocktails especially for you!',
                'is_popular' => false,
                'category_order' => 19,
                'category_id' => null,
                'is_show' => 0,
                'product_type_id' => null,
                'created_at' => '2021-03-25 16:49:59',
                'updated_at' => '2024-02-27 12:17:02',
                'deleted_at' => null,
            ],
            [
                'id' => 26,
                'category_name' => 'Rum Dada',
                'image' => '',
                'description' => 'Selection of the smoothest rums.',
                'is_popular' => false,
                'category_order' => 17,
                'category_id' => null,
                'is_show' => 0,
                'product_type_id' => null,
                'created_at' => '2021-03-25 17:04:11',
                'updated_at' => '2024-02-27 12:17:02',
                'deleted_at' => null,
            ],
            [
                'id' => 27,
                'category_name' => 'Liqueur',
                'image' => '',
                'description' => 'Likeuren, bittere en meer bijzondere smaken',
                'is_popular' => false,
                'category_order' => 14,
                'category_id' => null,
                'is_show' => 0,
                'product_type_id' => null,
                'created_at' => '2021-03-25 19:38:33',
                'updated_at' => '2024-02-27 12:17:02',
                'deleted_at' => null,
            ],
            [
                'id' => 28,
                'category_name' => 'Sub Wijn',
                'image' => '1623159360_1613235478_bierprijzen-flessen.png',
                'description' => 'Description',
                'is_popular' => false,
                'category_order' => 1,
                'category_id' => 14,
                'is_show' => 1,
                'product_type_id' => null,
                'created_at' => '2021-06-08 17:06:00',
                'updated_at' => '2021-10-19 20:38:08',
                'deleted_at' => '2021-10-19 20:38:08',
            ],
            [
                'id' => 29,
                'category_name' => 'Sub Vodka',
                'image' => '1623159442_1616660241_PhotoRoom-20210325_091625.png',
                'description' => 'Description',
                'is_popular' => false,
                'category_order' => 2,
                'category_id' => 4,
                'is_show' => 1,
                'product_type_id' => null,
                'created_at' => '2021-06-08 17:07:22',
                'updated_at' => '2021-06-08 17:07:22',
                'deleted_at' => null,
            ],
            [
                'id' => 30,
                'category_name' => 'Sparkling sub',
                'image' => '',
                'description' => 'Sparkling sub is nice product.',
                'is_popular' => false,
                'category_order' => 3,
                'category_id' => 15,
                'is_show' => 1,
                'product_type_id' => null,
                'created_at' => '2021-06-08 17:29:36',
                'updated_at' => '2021-09-20 15:39:30',
                'deleted_at' => '2021-09-20 15:39:30',
            ],
            [
                'id' => 31,
                'category_name' => 'Sparkling sub2',
                'image' => '',
                'description' => 'Sparkling sub2 is nice products.',
                'is_popular' => false,
                'category_order' => 4,
                'category_id' => 15,
                'is_show' => 1,
                'product_type_id' => null,
                'created_at' => '2021-06-09 09:22:36',
                'updated_at' => '2021-09-20 15:36:16',
                'deleted_at' => '2021-09-20 15:36:16',
            ],
            [
                'id' => 32,
                'category_name' => 'jghjg',
                'image' => '1625921485_plan_image (4).png',
                'description' => 'hjghj',
                'is_popular' => false,
                'category_order' => 5,
                'category_id' => 14,
                'is_show' => 1,
                'product_type_id' => null,
                'created_at' => '2021-07-10 16:21:25',
                'updated_at' => '2021-09-20 10:55:52',
                'deleted_at' => '2021-09-20 10:55:52',
            ],
            [
                'id' => 40,
                'category_name' => 'Shots',
                'image' => '',
                'description' => 'lekkerste shots vers klaargemaakt voor jouw gemak.',
                'is_popular' => false,
                'category_order' => 20,
                'category_id' => null,
                'is_show' => 1,
                'product_type_id' => null,
                'created_at' => '2021-10-19 21:46:26',
                'updated_at' => '2024-02-27 12:17:02',
                'deleted_at' => null,
            ],
            [
                'id' => 38,
                'category_name' => 'Alcoholvrij',
                'image' => '',
                'description' => 'Smaakvolle 0,0 procent alcoholvrije dranken wijn, bier, radlers, bubbels......',
                'is_popular' => false,
                'category_order' => 13,
                'category_id' => null,
                'is_show' => 1,
                'product_type_id' => 18,
                'created_at' => '2021-10-15 13:59:40',
                'updated_at' => '2024-02-27 12:17:02',
                'deleted_at' => null,
            ],
            [
                'id' => 33,
                'category_name' => 'Sub Cat',
                'image' => '1627280338_1569926682images 7.jpg',
                'description' => 'Just for test',
                'is_popular' => false,
                'category_order' => 1,
                'category_id' => null,
                'is_show' => 1,
                'product_type_id' => null,
                'created_at' => '2021-07-26 08:24:32',
                'updated_at' => '2021-09-16 14:52:25',
                'deleted_at' => '2021-09-16 14:52:25',
            ],
            [
                'id' => 34,
                'category_name' => 'New Cat from sub cat',
                'image' => '',
                'description' => 'test',
                'is_popular' => false,
                'category_order' => 22,
                'category_id' => 33,
                'is_show' => 1,
                'product_type_id' => null,
                'created_at' => '2021-07-26 09:50:06',
                'updated_at' => '2021-09-16 14:52:25',
                'deleted_at' => '2021-09-16 14:52:25',
            ],
            [
                'id' => 35,
                'category_name' => 'price',
                'image' => '',
                'description' => 'ew',
                'is_popular' => false,
                'category_order' => 23,
                'category_id' => 33,
                'is_show' => 0,
                'product_type_id' => null,
                'created_at' => '2021-07-26 09:50:49',
                'updated_at' => '2021-07-26 09:53:44',
                'deleted_at' => '2021-07-26 09:53:44',
            ],
            [
                'id' => 36,
                'category_name' => 'Pizza',
                'image' => '',
                'description' => 'Test Category',
                'is_popular' => false,
                'category_order' => 22,
                'category_id' => null,
                'is_show' => 1,
                'product_type_id' => null,
                'created_at' => '2021-07-27 13:46:21',
                'updated_at' => '2021-09-16 14:52:03',
                'deleted_at' => '2021-09-16 14:52:03',
            ],
            [
                'id' => 37,
                'category_name' => 'Jack Daniel\'s',
                'image' => '',
                'description' => 'test',
                'is_popular' => false,
                'category_order' => 21,
                'category_id' => null,
                'is_show' => 1,
                'product_type_id' => null,
                'created_at' => '2021-09-20 08:48:40',
                'updated_at' => '2021-09-20 11:26:15',
                'deleted_at' => '2021-09-20 11:26:15',
            ],
            [
                'id' => 39,
                'category_name' => 'Kratten bier',
                'image' => '',
                'description' => 'Kratten bier',
                'is_popular' => false,
                'category_order' => 21,
                'category_id' => null,
                'is_show' => 0,
                'product_type_id' => 1,
                'created_at' => '2021-10-19 18:30:14',
                'updated_at' => '2024-02-27 12:17:02',
                'deleted_at' => null,
            ],
        ]);
    }
}
